name: xiu_to_xiandi_tuixiu
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_markdown: ^0.6.14
  flutter_animate: ^4.3.0
  animated_text_kit: ^4.2.2
  fl_chart: ^0.63.0
  flutter_glow: ^0.3.2
  rive: ^0.11.0
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  newton_particles: ^0.2.2
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/