final List<Map<String, dynamic>> initialDiscipleRawPool = [
  {'name': '苏眠', 'aptitude': 31},
  {'name': '青璃', 'aptitude': 32},
  {'name': '柳莺', 'aptitude': 33},
  {'name': '洛雪', 'aptitude': 34},
  {'name': '南芙', 'aptitude': 35},
  {'name': '林潇', 'aptitude': 36},
  {'name': '唐霜', 'aptitude': 37},
  {'name': '瑶烟', 'aptitude': 38},
  {'name': '白语', 'aptitude': 39},
  {'name': '夜妍', 'aptitude': 40},
  {'name': '初月', 'aptitude': 41},
  {'name': '沐芊', 'aptitude': 42},
  {'name': '凤灵', 'aptitude': 43},
  {'name': '紫嫣', 'aptitude': 44},
  {'name': '慕雪', 'aptitude': 45},
  {'name': '叶凝', 'aptitude': 46},
  {'name': '楚瑶', 'aptitude': 47},
  {'name': '云绮', 'aptitude': 48},
  {'name': '绾青', 'aptitude': 49},
  {'name': '白栀', 'aptitude': 50},
  {'name': '星璃', 'aptitude': 51},
  {'name': '雪舞', 'aptitude': 52},
  {'name': '浅悠', 'aptitude': 53},
  {'name': '璃音', 'aptitude': 54},
  {'name': '锦瑶', 'aptitude': 55},
  {'name': '梦婉', 'aptitude': 56},
  {'name': '宛凝', 'aptitude': 57},
  {'name': '霜月', 'aptitude': 58},
  {'name': '依萝', 'aptitude': 59},
  {'name': '婉晴', 'aptitude': 60},
  {'name': '云汐', 'aptitude': 61},
  {'name': '月绮', 'aptitude': 62},
  {'name': '妍溪', 'aptitude': 63},
  {'name': '竹音', 'aptitude': 64},
  {'name': '烟萝', 'aptitude': 65},
  {'name': '凌梦', 'aptitude': 66},
  {'name': '绫华', 'aptitude': 67},
  {'name': '晴澜', 'aptitude': 68},
  {'name': '紫鸢', 'aptitude': 69},
  {'name': '宸雪', 'aptitude': 70},
  {'name': '悠然', 'aptitude': 71},
  {'name': '夜璃', 'aptitude': 72},
  {'name': '雨绮', 'aptitude': 73},
  {'name': '珞晴', 'aptitude': 74},
  {'name': '羽然', 'aptitude': 75},
  {'name': '珂儿', 'aptitude': 76},
  {'name': '璃歌', 'aptitude': 77},
  {'name': '梦溪', 'aptitude': 78},
  {'name': '楚然', 'aptitude': 79},
  {'name': '雪瑶', 'aptitude': 80},
  {'name': '灵儿', 'aptitude': 81},
  {'name': '姝妍', 'aptitude': 82},
  {'name': '曦月', 'aptitude': 83},
  {'name': '馨兰', 'aptitude': 84},
  {'name': '泠音', 'aptitude': 85},
  {'name': '绮梦', 'aptitude': 86},
  {'name': '静婉', 'aptitude': 87},
  {'name': '月凝', 'aptitude': 88},
  {'name': '依雪', 'aptitude': 89},
  {'name': '蓝澜', 'aptitude': 90},
].map((entry) {
  final int aptitude = entry['aptitude'] as int;
  return {
    'name': entry['name'],
    'gender': 'female',
    'aptitude': aptitude,
    'hp': 100 + (aptitude - 31),
    'atk': 20 + (aptitude - 31),
    'def': 10 + (aptitude - 31),
    'age': 0,
    'imagePath': 'assets/images/$aptitude.png',
  };
}).toList();
