// ✅ 文件：lib/services/ssr_disciple_pool.dart

/// 纯数据池，不引用 Disciple 类，供招募时再封装
final List<Map<String, dynamic>> ssrDiscipleRawPool = [
  {
    'name': '黄芷',
    'gender': 'female',
    'aptitude': 81,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 15,
    'imagePath': 'assets/images/dujie_1.png',
  },
  {
    'name': '柳婉',
    'gender': 'female',
    'aptitude': 82,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 18,
    'imagePath': 'assets/images/dujie_2.png',
  },
  {
    'name': '云悠',
    'gender': 'female',
    'aptitude': 83,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 17,
    'imagePath': 'assets/images/dujie_3.png',
  },
  {
    'name': '苏绮',
    'gender': 'female',
    'aptitude': 84,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 18,
    'imagePath': 'assets/images/dujie_4.png',
  },
  {
    'name': '叶璃',
    'gender': 'female',
    'aptitude': 85,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 14,
    'imagePath': 'assets/images/dujie_5.png',
  },
  {
    'name': '夜婉',
    'gender': 'female',
    'aptitude': 86,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 12,
    'imagePath': 'assets/images/dujie_6.png',
  },
  {
    'name': '凌萱',
    'gender': 'female',
    'aptitude': 87,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 18,
    'imagePath': 'assets/images/dujie_7.png',
  },
  {
    'name': '慕语',
    'gender': 'female',
    'aptitude': 88,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 18,
    'imagePath': 'assets/images/dujie_8.png',
  },
  {
    'name': '南絮',
    'gender': 'female',
    'aptitude': 89,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 16,
    'imagePath': 'assets/images/dujie_9.png',
  },
  {
    'name': '温青',
    'gender': 'female',
    'aptitude': 90,
    'hp': 100,
    'atk': 20,
    'def': 10,
    'age': 14,
    'imagePath': 'assets/images/dujie_10.png',
  },
];
