import 'dart:math';
import 'dart:ui';
import 'package:flame/components.dart';

import '../../../utils/name_generator.dart';
import '../dynamic_sprite_entry.dart';
import '../floating_island_dynamic_spawner_component.dart';
import '../floating_island_static_spawner_component.dart';
import '../noise_tile_map_generator.dart';
import '../static_sprite_entry.dart';

class BeachDecorator extends Component {
  final Component grid;
  final Vector2 Function() getLogicalOffset;
  final Vector2 Function() getViewSize;
  final NoiseTileMapGenerator noiseMapGenerator;
  final int seed;

  BeachDecorator({
    required this.grid,
    required this.getLogicalOffset,
    required this.getViewSize,
    required this.noiseMapGenerator,
    required this.seed,
  });

  @override
  Future<void> onLoad() async {
    final List<String> taunts = [
      "滚开！",
      "你算哪根葱？",
      "别来碍眼！",
      "找抽是不是？",
      "你有病啊？",
      "离远点！",
      "再碰试试！",
      "不知死活！",
      "废物！",
      "真烦人！",
      "别碰我！",
      "想死啊？",
      "蠢货！",
      "没长眼？",
      "真讨厌！",
      "走开！",
      "不配和我比！",
      "自取其辱！",
      "又来？",
      "死远点！",
      "啧，丢人！",
      "还敢过来？",
      "好胆再来！",
      "没完没了！",
      "再靠近试试！",
      "少废话！",
      "一边去！",
      "不自量力！",
      "别烦我！",
      "你也配？",
      "我看你是欠收拾！",
      "就这？",
      "看清楚是谁！",
      "再嚣张试试！",
      "没点本事还嚷嚷？",
      "滚蛋！",
      "你找错人了！",
      "想清楚后果！",
      "自取灭亡！",
      "小心我打爆你！",
      "你是聋了吗？",
      "谁给你的勇气？",
      "怂货！",
      "白痴！",
      "下一个！",
      "还想来？",
      "真没劲！",
      "可笑！",
      "愚蠢至极！",
      "还不死心？",
      "你累不累？",
      "笑死人！",
      "小丑罢了！",
      "给你脸了？",
      "废话真多！",
      "别蹭存在感！",
      "再动试试！",
      "呸，滚开！",
      "你瞎啊？",
      "有本事放马过来！",
      "就你？也配？",
      "回去练几年再来！",
      "识相的快滚！",
      "不怕死就上！",
      "我等你动手！",
      "来啊，别怂！",
      "你以为你是谁？",
      "你太弱了！",
      "别挡路！",
      "废话少说，开打！",
      "再瞪我试试！",
      "敢碰我？",
      "就这点实力？",
      "我一根手指头捏死你！",
      "不服来战！",
      "别在我面前丢人现眼！",
      "看我不削死你！",
      "给我爬！",
      "快滚，免得丢命！",
      "啧，真丑陋！",
      "小心我一巴掌拍扁你！",
      "没点分量别来找抽！",
      "滚远点，别脏了我的眼！",
      "还敢嘚瑟？",
      "让你三招都赢不了！",
      "给脸不要脸！",
      "你算个什么东西？",
      "来啊，互相伤害啊！",
      "再装逼试试！",
      "找虐吗？",
      "不自量力的东西！",
      "胆子挺肥啊！",
      "我看你活腻了！",
      "有多远滚多远！",
      "废物一个！",
      "别当小丑！",
      "别在这叫唤！",
      "一碰就碎，呵！",
      "谁惯着你了？",
      "你能耐也就这样？",
      "有种别跑啊！",
      "说完了？轮到我了！",
      "滚开，别碍事！",
      "你配和我说话？",
      "笑死，蠢到家了！",
      "你这点实力拿出来丢人？",
      "谁给你的勇气？梁静茹？",
      "来啊，看谁先怂！",
      "见一次打一次！",
      "就你？不够看！",
      "活该被虐！",
      "有种就别哭！",
      "怕了就滚！",
      "没资格站在这！",
      "快去练几年再来！",
      "不想死就滚！",
      "当我是摆设？",
      "我手痒了！",
      "少跟我废话！",
      "嘴硬有用？",
      "你是来搞笑的？",
      "动动脑子再来！",
      "要不要先找点帮手？",
      "看好了，这就叫实力！",
      "连个招呼都接不住！",
      "你怎么还活着？",
      "懒得理你！",
      "想清楚后果！",
      "别把自己当回事！",
      "三秒钟解决你！",
      "站这碍眼！",
      "本事呢？露一个看看！",
      "一边凉快去！",
      "瞧不起你！",
      "真是白费口舌！",
      "死性不改啊？",
      "又来送人头？",
      "赶紧滚蛋！",
      "就这点胆子？",
      "可怜虫一个！",
      "废材！",
      "闭嘴！",
      "笑掉大牙！",
      "小小蝼蚁！",
      "滚远点，别丢人！",
      "你有脸说话？",
      "这智商，堪忧！",
      "丢人现眼的东西！",
    ];

    add(
      FloatingIslandStaticSpawnerComponent(
        grid: grid,
        getLogicalOffset: getLogicalOffset,
        getViewSize: getViewSize,
        getTerrainType: (pos) => noiseMapGenerator.getTerrainTypeAtPosition(pos),
        allowedTerrains: {'beach'},
        staticSpritesMap: {
          'beach': [
            StaticSpriteEntry('floating_island/beach_1.png', 1),
          ],
        },
        staticTileSize: 100.0,
        seed: seed,
        minCount: 10,
        maxCount: 20,
        minSize: 16.0,
        maxSize: 48.0,
      ),
    );

    add(
      FloatingIslandDynamicSpawnerComponent(
        grid: grid,
        getLogicalOffset: getLogicalOffset,
        getViewSize: getViewSize,
        getTerrainType: (pos) => noiseMapGenerator.getTerrainTypeAtPosition(pos),
        noiseMapGenerator: noiseMapGenerator,
        allowedTerrains: {'beach'},
        dynamicSpritesMap: {
          'beach': [
            DynamicSpriteEntry(
              'floating_island/npc_1.png',
              1,
              generateRandomLabel: true, // 🌟随机生成名字
              labelFontSize: 10,
              labelColor: const Color(0xFF000000),
              minDistance: 500.0,
              maxDistance: 5000.0,
              collisionTexts: taunts,
              desiredWidth: 32,
            ),
          ],
        },
        dynamicTileSize: 256.0,
        seed: seed,
        minDynamicObjectsPerTile: 3,
        maxDynamicObjectsPerTile: 5,
        minSpeed: 15.0,
        maxSpeed: 55.0,
      ),
    );
  }
}
